name: gui-snake # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Quick GUI snake game snap # 79 char long summary
description: |
  This is gui-snake snap. It is the snake game with a super simple GUI.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

build-packages:
  - pkg-config
  - python
  - pip

parts:
  gui-snake:
    plugin: python
    python-packages:
      - pygame
      - wheel
    source: gui-snake/
    stage-packages:
      - libgl1
      - libgl1-mesa-dri
      - libgl1-mesa-dev
      - libgles2-mesa-dev
      - mesa-utils
      - libgle3
      - libglu1-mesa-dev
      - libice6
      - libsm6
      - libx11-6
      - libxext6
      - libxcb-util1
      - libxcb-dri3-0
      - mesa-utils-extra
      - libglapi-mesa
      - libglvnd-dev

apps:
  gui-snake:
    command: bin/python gui-snake/__init__.py
    # extensions: [gnome-3-38]
    plugs:
      - desktop
      - desktop-legacy
      - opengl    
